[project]
name = 'deadswitch'
description = '''Your secrets outlive your silence - Bitcoin heartbeat-based dead man's switch'''
authors = ['man-croft']
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.nft-trait]
path = 'contracts/nft-trait.clar'
clarity_version = 4
epoch = 'latest'

[contracts.heartbeat-core]
path = 'contracts/heartbeat-core.clar'
clarity_version = 4
epoch = 'latest'

[contracts.vault]
path = 'contracts/vault.clar'
clarity_version = 4
epoch = 'latest'

[contracts.beneficiary-mgr]
path = 'contracts/beneficiary-mgr.clar'
clarity_version = 4
epoch = 'latest'

[contracts.beneficiary-mgr-v2]
path = 'contracts/beneficiary-mgr-v2.clar'
clarity_version = 4
epoch = 'latest'

[contracts.beneficiary-migration]
path = 'contracts/beneficiary-migration.clar'
clarity_version = 4
epoch = 'latest'

[contracts.guardian-network]
path = 'contracts/guardian-network.clar'
clarity_version = 4
epoch = 'latest'

[contracts.trigger-actions]
path = 'contracts/trigger-actions.clar'
clarity_version = 4
epoch = 'latest'

[contracts.switch-nft]
path = 'contracts/switch-nft.clar'
clarity_version = 4
epoch = 'latest'

[repl.analysis]
passes = [
    'check_checker',
    'call_checker',
]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
